homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elev
  unit_system: metric
  time_zone: Europe/Amsterdam
  name: Home
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  auth_mfa_modules:
    - type: totp
  whitelist_external_dirs:
    - /config

default_config:
hassio:

http:
discovery:

lovelace:
  mode: yaml
  resources:
    !include lovelace/resources/resources.yaml

  # custom_header:
  #   compact_mode: true

  # decluttering_templates:
  #   !include lovelace/decluttering_templates/decluttering_templates.yaml

  dashboards:
    lovelace-yaml:
      mode: yaml
      title: YAML
      icon: mdi:view-dashboard
      show_in_sidebar: true
      filename: lovelace.yaml

    lovelace_mobile:
      mode: yaml
      title: Mobile
      icon: mdi:cellphone_android
      show_in_sidebar: true
      filename: lovelace_mobile.yaml

customizer:
  custom_ui: hosted

browser_mod:

frontend:
  themes: !include_dir_merge_named ../themes

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

scene: !include scenes.yaml
notify: !include notify/notify.yaml

ffmpeg: