homeassistant:
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
  whitelist_external_dirs:
    - /config

automation: !include automations.yaml
logbook: !include logbook.yaml
history: !include history.yaml
group: !include groups.yaml
scene: !include scenes.yaml
frontend: !include frontend.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
switch: !include switches.yaml
device_tracker: !include device_trackers.yaml
script: !include scripts.yaml
notify: !include notify.yaml
recorder:

system_health:
discovery:
  ignore:
    - apple_tv
config:

lovelace:
  mode: yaml

http:

hacs:
  token: !secret hacs_token

sun:

cloud:

person:

climate:
  platform: nest

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: samsungtv
    mac: !secret samsungtv_mac
    host: !secret samsungtv_host
    name: Master Bedroom TV
    port: 8001

apple_tv:
  - host: !secret apple_tv_host
    login_id: !secret apple_tv_login_id
    name: Master Bedroom Apple TV
    start_off: false

map:

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

proximity:
  home:
    devices:
      - person.dennis
      - person.stephanie
    tolerance: 50
    unit_of_measurement: km
    
weather:
  - platform: buienradar
    name: "Lopik-Cabauw"
    
logger:
  default: warn

life360:
  driving_speed: 30
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  warning_threshold: 2
  error_threshold: 3
    
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
    
ring:
  username: !secret ring_username
  password: !secret ring_password

ffmpeg:

influxdb:
  host: !secret influxdb_host
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    entities:
       - sensor.living_room_thermostat_temperature
       - sensor.living_room_thermostat_humidity

camera:
  - platform: ring
  - platform: generic
    name: Buienradar
    still_image_url: https://api.buienradar.nl/image/1.0/RadarMapNL?w=480&h=480
    content_type: 'image/gif'
  - platform: generic
    name: Meteogram
    still_image_url: !secret meteogram_png_url
  - platform: generic
    name: Waqi
    still_image_url: !secret waqi_png_url
  - platform: generic
    name: sunmap
    still_image_url: https://www.timeanddate.com/scripts/sunmap.php?earth=1

konnected:
  access_token: !secret konnected_access_token
  api_host: !secret konnected_api_host
  devices:
    - id: !secret konnected_device_id
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Entryway'
        - zone: 2
          type: motion
          name: 'Kitchen'
        - zone: 3
          type: motion
          name: 'Living Room'
        - zone: 4
          type: motion
          name: 'Office'
        - zone: 5
          type: motion
          name: 'Garage'
      switches:
        - zone: out
          name: 'Siren'
   
alarm_control_panel:
  - platform: manual
    name: Konnected Alarm
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 300
      delay_time: 20
  - platform: alexa_media
    name: Alexa Guard
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 300
      delay_time: 20
