homeassistant:
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  auth_mfa_modules:
    - type: totp
  whitelist_external_dirs:
    - /config

config:
hassio:
system_health:
#ssdp:
#zeroconf:
http:
discovery:

# ########################################
# ###           ASSISTANT             ###
# ########################################
cloud:

# ########################################
# ###             MOBILE               ###
# ########################################
#ios: !include notify/ios_config.yaml
#mobile_app:

# ########################################
# ###                GUI               ###
# ########################################
lovelace:
  mode: yaml

#customizer:
#  custom_ui: hosted

map:

frontend:
  extra_html_url:
    - /local/hass-bha-icons.html
    
#panel_custom: !include panels/panel_custom.yaml

hacs:
  token: !secret hacs_token
#  appdaemon: true
  

browser_mod:
#  devices:
#    24d2e744-aee3dfdb:
#      name: Isa laptop
#    82ce1407-06ba38e8:
#      name: Dashboard
#    49b3d945-27efcb05:
#      name: Isa PC
      
# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

# ########################################
# ###              ENTITIES             ###
# ########################################
person: !include entities/person.yaml
media_player: !include entities/media_player.yaml
device_tracker: !include entities/device_tracker.yaml

# ########################################
# ###             SERVICES             ###
# ########################################
sun:
notify: !include notify/notify.yaml

ffmpeg: