homeassistant:
  # latitude: !secret home_lat
  # longitude: !secret home_long
  # elevation: !secret home_elev
  # unit_system: metric
  # time_zone: Europe/Amsterdam
  # name: Home
  packages: !include_dir_named packages
  auth_mfa_modules:
    - type: totp
  allowlist_external_dirs:
    - /config

default_config:
hassio:

http:
discovery:

lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes

automation blueprints: !include automations.yaml

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

scene: !include scenes.yaml
notify: !include notify/notify.yaml

ffmpeg:
