homeassistant:
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  auth_mfa_modules:
    - type: totp
  whitelist_external_dirs:
    - /config

default_config:
hassio:
http:
discovery:

lovelace:
  mode: yaml

customizer:
  custom_ui: hosted

browser_mod:

frontend:
  extra_html_url:
    - /local/hass-bha-icons.html
    
recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

scene: !include scenes.yaml
automation old: !include automations.yaml
notify: !include notify/notify.yaml

ffmpeg: