esphome:
  name: hallway_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret esphome_wifi_1_ssid
  password: !secret esphome_wifi_1_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hallway Light Fallback Hotspot"
    password: !secret esphome_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_ota_password

ota:
  password: !secret esphome_ota_password
